wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1650641279
    t:
      1:
      - 55
      3:
      - 16
      4: 3.8.5
      5: 0.12.15
      8:
      - 1
      - 5
lambd1:
  desc: null
  value: 0
